version: '3'
services:
  api:
    image: trade:v1
    ports:
     - "5001:5001"
    volumes:
     - D:/Projects/BigData/TradeAdvisor-0.0.1/trade_advisor/data/local/collector:/app/data
    command: api
  ws:
    image: trade:v2
    ports:
     - "10006:10006"
    command: ws