version: '3'
services:
  api:
    image: trade:v0
    ports:
     - "5000:5000"
    volumes:
     - C:/Trung/Projects/BigData/trade_advisor/data:/app/data
    command: api
  ws:
    image: trade:v0
    ports:
     - "10005:10005"
    command: ws