version: '3'
services:
  api:
    image: trade:v1
    ports:
     - "5000:5000"
    volumes:
     - D:/Projects/BigData/TradeAdvisor-0.0.1/trade_advisor/data/local:/app/data
    command: api
  ws:
    image: trade:v1
    ports:
     - "10005:10005"
    command: ws