version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs//info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs//errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    urllib3:
        level: ERROR
        handlers: [console]
        propagate: no

    chardet:
        level: ERROR
        handlers: [console]
        propagate: no

    controller.scrapper_controller:
        level: DEBUG
        handlers: [console]
        propagate: no

    headline_sentiment_analysis.sentiment_analyzer:
        level: DEBUG
        handlers: [console]
        propagate: no

    scrapper.scheduled_scrapper:
        level: DEBUG
        handlers: [console]
        propagate: no

    scrapper.scrapper:
        level: DEBUG
        handlers: [console]
        propagate: no

    scrapper.get_request:
        level: DEBUG
        handlers: [console]
        propagate: no

    utils.date_time:
        level: DEBUG
        handlers: [console]
        propagate: no

    utils.ticker_symbol:
        level: DEBUG
        handlers: [console]
        propagate: no

    utils.xpath:
        level: DEBUG
        handlers: [console]
        propagate: no

    websocket.ws_server:
        level: INFO
        handlers: [console]
        propagate: no
root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]