version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs//info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs//errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    urllib3:
        level: ERROR
        handlers: [console]
        propagate: no

    chardet:
        level: ERROR
        handlers: [console]
        propagate: no

    pattern_matcher:
        controller:
            level: INFO
            handlers: [console]
            propagate: no
        loader:
            level: INFO
            handlers: [console]
            propagate: no
        mather:
            level: INFO
            handlers: [console]
            propagate: no
        measurement:
            level: INFO
            handlers: [console]
            propagate: no
        processor:
            level: INFO
            handlers: [console]
            propagate: no
        runner:
            level: INFO
            handlers: [console]
            propagate: no
        utils:
            level: INFO
            handlers: [console]
            propagate: no

    web_scrapper:
        controller:
            level: INFO
            handlers: [console]
            propagate: no
        headline_sentiment_analysis:
            level: INFO
            handlers: [console]
            propagate: no
        scrapper:
            level: INFO
            handlers: [console]
            propagate: no
        utils:
            level: INFO
            handlers: [console]
            propagate: no
        websocket:
            level: INFO
            handlers: [console]
            propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]