version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs//info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs//errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    urllib3:
        level: ERROR
        handlers: [console, error_file_handler]
        propagate: no

    chardet:
        level: ERROR
        handlers: [console, error_file_handler]
        propagate: no

    data_collector:
        level: INFO
        handlers: [console, info_file_handler]
        propagate: no

    pattern_matcher:
        level: INFO
        handlers: [console, info_file_handler]
        propagate: no

    web_scrapper:
        level: INFO
        handlers: [console, info_file_handler]
        propagate: no

    price_predictor:
        level: INFO
        handlers: [console, info_file_handler]
        propagate: no   

    test:
        level: INFO
        handlers: [console, info_file_handler]
        propagate: no
        

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]