version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: pattern-matching.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    conf:
        level: INFO
        handlers: [console, file_handler]
        propagate: no
    loader:
        level: INFO
        handlers: [console, file_handler]
        propagate: no
    matcher:
        level: INFO
        handlers: [console, file_handler]
        propagate: no
    measurements:
        level: INFO
        handlers: [console, file_handler]
        propagate: no
    runner:
        level: INFO
        handlers: [console, file_handler]
        propagate: no
    processor:
        level: INFO
        handlers: [console, file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, file_handler]